# Generated by Django 6.0.2 on 2026-02-18 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sched_date', models.CharField(blank=True, default='', max_length=200)),
                ('sched_time', models.CharField(blank=True, default='', max_length=20)),
                ('sched_status', models.BooleanField(default=False)),
                ('sched_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.doctorprofile')),
                ('sched_patient', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.patientprofile')),
            ],
        ),
    ]
