# Generated by Django 6.0.2 on 2026-03-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleinfo',
            name='sched_img',
            field=models.ImageField(blank=True, null=True, upload_to='something/'),
        ),
    ]
