# Generated by Django 6.0.2 on 2026-03-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_scheduling', '0002_scheduleinfo_sched_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleinfo',
            name='sched_status_complete',
            field=models.BooleanField(default=False),
        ),
    ]
