# Generated by Django 6.0.2 on 2026-02-18 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(default='', max_length=200)),
                ('doctor_age', models.IntegerField()),
                ('doctor_role', models.CharField(default='', max_length=100)),
                ('doctor_schedule_date_begin', models.DateField(verbose_name='')),
                ('doctor_schedule_date_end', models.DateField(verbose_name='')),
                ('doctor_schedule_time', models.TimeField(verbose_name='')),
                ('doctor_img', models.ImageField(blank=True, default='', null=True, upload_to='doctors/')),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pat_name', models.CharField(max_length=200)),
                ('pat_age', models.IntegerField()),
                ('pat_recentSched', models.DateTimeField(blank=True, null=True)),
                ('schedule_req_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('pat_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.doctorprofile')),
                ('pat_user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
