# Generated by Django 6.0.2 on 2026-02-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_doctorprofile_doctor_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='doctor_schedule_date_begin',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='doctor_schedule_date_end',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='doctor_schedule_time',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='doctor_available_days',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='doctor_schedule_time_end',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='doctor_schedule_time_start',
            field=models.TimeField(default='00:00'),
        ),
    ]
