# Generated by Django 6.0.2 on 2026-02-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_patientprofile_pat_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='pat_img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='patients/'),
        ),
    ]
