# Generated by Django 6.0.2 on 2026-03-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_patientprofile_pat_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='clinic_latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='clinic_longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='clinic_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
