# Generated by Django 6.0.2 on 2026-02-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_pat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_username', models.CharField(max_length=254)),
                ('user_password', models.CharField(max_length=254)),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
